name: Trigger kobuki_docker

on:
    push:
        branches: 
          - main

    pull_request:
        branches: 
          - main


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Kobuki Docker Repository
        run: |
          # Set the required variables
          repo_owner="airesearchlab" 
          repo_name="kobuki_docker"  
          event_type="trigger-workflow" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"